//! Interop against **Credo**, the reference DIDComm v1 implementation.
//!
//! # What is checked here, and what it proves
//!
//! `tests/fixtures/credo.json` holds envelopes produced by a live Credo 0.6.3
//! agent (askar 0.4.3) driving its real `DidCommEnvelopeService.packMessage` —
//! the same code path a Credo wallet uses on the wire. The fixtures are
//! regenerated by `interop/didcomm-v1`, a developer-only harness following the
//! precedent set by `interop/` for the TSP reference implementation; CI needs
//! no Node, because the envelopes are committed bytes.
//!
//! Opening a Credo envelope is a strong test precisely because every detail has
//! to be right at once. There is no partial credit: a wrong base64 variant, a
//! trailing instead of leading `crypto_box` MAC, a missing HSalsa20 step, the
//! wrong sealed-box nonce derivation, a 24-byte content nonce instead of 12, or
//! the AAD taken over decoded rather than encoded header bytes each produce a
//! decrypt failure and nothing else.
//!
//! # Direction coverage
//!
//! - **Credo -> this crate** is covered here, in CI, against committed bytes.
//!   This is also the security-critical direction: it is where an attacker's
//!   input arrives.
//! - **This crate -> Credo** cannot be asserted without running Credo, so it
//!   lives in the harness. [`emit_envelopes_for_credo`] writes this crate's
//!   output to `interop/didcomm-v1/rust-envelopes.json`, and the harness feeds
//!   it back through Credo's `unpackMessage`. Both directions were verified
//!   green when these fixtures were generated; see the crate CHANGELOG.

use std::collections::BTreeMap;

use affinidi_messaging_didcomm_v1::message::pack;
use affinidi_messaging_didcomm_v1::message::unpack::{NoBindings, unpack};
use affinidi_messaging_didcomm_v1::protocols::basic_message::{self, BasicMessage};
use affinidi_messaging_didcomm_v1::protocols::forward;
use affinidi_messaging_didcomm_v1::{
    DIDCommV1Store, MessageV1, PrivateIdentity, ResolvedIdentity, UnpackResult, Verkey,
};
use serde::Deserialize;
use serde_json::Value;

const FIXTURES: &str = include_str!("fixtures/credo.json");

#[derive(Debug, Deserialize)]
struct Fixtures {
    parties: Vec<PartyFixture>,
    cases: Vec<CaseFixture>,
}

#[derive(Debug, Deserialize)]
struct PartyFixture {
    name: String,
    /// The raw Ed25519 seed (the OKP JWK `d` parameter), hex-encoded.
    signing_key_hex: String,
    verkey_base58: String,
}

#[derive(Debug, Deserialize)]
struct CaseFixture {
    name: String,
    envelope: Value,
    expected_plaintext: Value,
    sender_verkey_base58: Option<String>,
    recipient_verkey_base58: String,
    #[serde(default)]
    forwarded_to: Option<String>,
    #[serde(default)]
    mediator_verkey_base58: Option<String>,
}

/// Credo writes camelCase; map it once here rather than renaming every field.
fn fixtures() -> Fixtures {
    let raw: Value = serde_json::from_str(FIXTURES).expect("fixtures are valid JSON");
    serde_json::from_value(rename_keys(raw)).expect("fixtures match the expected shape")
}

fn rename_keys(value: Value) -> Value {
    match value {
        Value::Object(map) => Value::Object(
            map.into_iter()
                .map(|(key, val)| {
                    // Only the fixture wrapper is renamed; `envelope` and
                    // `expectedPlaintext` hold wire data that must not be touched.
                    let renamed = match key.as_str() {
                        "signingKeyHex" => "signing_key_hex".to_string(),
                        "verkeyBase58" => "verkey_base58".to_string(),
                        "expectedPlaintext" => "expected_plaintext".to_string(),
                        "senderVerkeyBase58" => "sender_verkey_base58".to_string(),
                        "recipientVerkeyBase58" => "recipient_verkey_base58".to_string(),
                        "forwardedTo" => "forwarded_to".to_string(),
                        "mediatorVerkeyBase58" => "mediator_verkey_base58".to_string(),
                        _ => key,
                    };
                    let val = if renamed == "envelope" || renamed == "expected_plaintext" {
                        val
                    } else {
                        rename_keys(val)
                    };
                    (renamed, val)
                })
                .collect(),
        ),
        Value::Array(items) => Value::Array(items.into_iter().map(rename_keys).collect()),
        other => other,
    }
}

/// Reconstruct each fixture party as a local identity, keyed by name.
fn parties(fixtures: &Fixtures) -> BTreeMap<String, PrivateIdentity> {
    fixtures
        .parties
        .iter()
        .map(|party| {
            let seed: [u8; 32] = hex::decode(&party.signing_key_hex)
                .expect("seed is hex")
                .try_into()
                .expect("seed is 32 bytes");
            let identity =
                PrivateIdentity::from_signing_key(&format!("did:example:{}", party.name), &seed)
                    .expect("identity builds from the seed");

            // The verkey this crate derives must equal the one Credo published,
            // or nothing else in this file means anything.
            assert_eq!(
                identity.verkey.to_base58(),
                party.verkey_base58,
                "derived verkey for {} disagrees with Credo",
                party.name
            );
            (party.name.clone(), identity)
        })
        .collect()
}

fn case<'a>(fixtures: &'a Fixtures, name: &str) -> &'a CaseFixture {
    fixtures
        .cases
        .iter()
        .find(|c| c.name == name)
        .unwrap_or_else(|| panic!("fixture case `{name}` is missing"))
}

fn envelope_json(case: &CaseFixture) -> String {
    serde_json::to_string(&case.envelope).expect("envelope re-serializes")
}

/// The fixture file must actually contain Credo output, not an empty stub.
#[test]
fn fixtures_are_present_and_self_consistent() {
    let fixtures = fixtures();
    assert!(
        fixtures.cases.len() >= 5,
        "expected the full Credo case set"
    );
    let _ = parties(&fixtures);
}

#[test]
fn opens_a_credo_authcrypt_envelope() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let case = case(&fixtures, "authcrypt_basic_message");

    let alice = &parties["alice"];
    let bob = &parties["bob"];

    let mut bindings = DIDCommV1Store::new();
    bindings.add_resolved(alice.to_resolved());

    let result = unpack(&envelope_json(case), &[bob], &bindings).expect("Credo envelope opens");
    let authenticated = result
        .require_authenticated()
        .expect("Credo authcrypt is attributable");

    assert_eq!(authenticated.sender.as_str(), "did:example:alice");
    assert_eq!(
        authenticated.sender_verkey.to_base58(),
        case.sender_verkey_base58.as_deref().unwrap()
    );
    assert_eq!(
        authenticated.recipient_verkey.to_base58(),
        case.recipient_verkey_base58
    );

    // The decrypted message must be byte-equal to what Credo packed, including
    // the decorators this crate does not model.
    let decrypted: Value =
        serde_json::from_slice(&authenticated.message.to_json().unwrap()).unwrap();
    assert_eq!(decrypted, case.expected_plaintext);
}

#[test]
fn opens_a_credo_anoncrypt_envelope_and_reports_no_sender() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let case = case(&fixtures, "anoncrypt_basic_message");
    let bob = &parties["bob"];

    // Bindings deliberately include Alice: an anoncrypt envelope must not be
    // attributed to her (or anyone) just because we know who she is.
    let mut bindings = DIDCommV1Store::new();
    bindings.add_resolved(parties["alice"].to_resolved());

    let result = unpack(&envelope_json(case), &[bob], &bindings).expect("Credo envelope opens");

    match &result {
        UnpackResult::Anoncrypt {
            recipient_verkey, ..
        } => {
            assert_eq!(recipient_verkey.to_base58(), case.recipient_verkey_base58);
        }
        other => panic!("expected Anoncrypt, got {other:?}"),
    }
    assert!(!result.is_authcrypt());
    assert!(result.require_authenticated().is_err());
}

/// A Credo message with no `~thread` decorator at all must stay that way: the
/// RFC 0008 default is applied on read, never written into the parsed message.
#[test]
fn preserves_credo_absent_thread_decorator() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let case = case(&fixtures, "authcrypt_no_thread_decorator");

    let mut bindings = DIDCommV1Store::new();
    bindings.add_resolved(parties["alice"].to_resolved());

    let message = unpack(&envelope_json(case), &[&parties["bob"]], &bindings)
        .unwrap()
        .into_message();

    assert_eq!(message.thread, None, "Credo sent no ~thread decorator");
    assert_eq!(message.explicit_thid(), None);
    assert!(message.thid_is_defaulted());
    assert_eq!(
        message.effective_thid(),
        message.id.as_str(),
        "the RFC 0008 default is the message @id"
    );

    // The round trip must not materialise a decorator Credo did not send.
    let reserialized: Value = serde_json::from_slice(&message.to_json().unwrap()).unwrap();
    assert_eq!(reserialized, case.expected_plaintext);
    assert!(reserialized.get("~thread").is_none());
}

/// The threaded fixture exercises the other half: `thid` and `pthid` set by
/// Credo inside `~thread` must come through as explicit, not defaulted.
#[test]
fn preserves_credo_thread_decorator() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let case = case(&fixtures, "authcrypt_basic_message");

    let mut bindings = DIDCommV1Store::new();
    bindings.add_resolved(parties["alice"].to_resolved());

    let message = unpack(&envelope_json(case), &[&parties["bob"]], &bindings)
        .unwrap()
        .into_message();

    assert_eq!(message.explicit_thid(), Some("thread-1"));
    assert_eq!(message.pthid_value(), Some("parent-1"));
    assert!(!message.thid_is_defaulted());

    assert!(basic_message::is_basic_message(&message));
    assert_eq!(
        basic_message::content(&message),
        Some("Your hovercraft is full of eels.")
    );
}

#[test]
fn opens_a_credo_multi_recipient_envelope_as_either_recipient() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let case = case(&fixtures, "authcrypt_multi_recipient");

    let mut bindings = DIDCommV1Store::new();
    bindings.add_resolved(parties["alice"].to_resolved());

    for name in ["bob", "mediator"] {
        let authenticated = unpack(&envelope_json(case), &[&parties[name]], &bindings)
            .unwrap_or_else(|e| panic!("{name} could not open the envelope: {e}"))
            .require_authenticated()
            .expect("attributable");
        assert_eq!(authenticated.sender.as_str(), "did:example:alice");
        assert_eq!(
            authenticated.recipient.as_str(),
            format!("did:example:{name}")
        );
    }
}

/// Credo's `routingKeys` path produces an anoncrypt forward wrapping an
/// authcrypt envelope. This crate must unwrap both layers and agree with Credo
/// on the forward's `to` / `msg` member names.
#[test]
fn unwraps_a_credo_mediator_forward() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let case = case(&fixtures, "authcrypt_forwarded_via_mediator");

    let mediator = &parties["mediator"];
    let bob = &parties["bob"];

    let mut bindings = DIDCommV1Store::new();
    bindings.add_resolved(parties["alice"].to_resolved());

    // Outer layer: anonymous to the mediator.
    let at_mediator =
        unpack(&envelope_json(case), &[mediator], &bindings).expect("mediator opens the forward");
    assert!(
        matches!(at_mediator, UnpackResult::Anoncrypt { .. }),
        "Credo anon-packs forwards, so the mediator learns nothing about the sender"
    );

    let forward_message = at_mediator.into_message();
    assert!(forward::is_forward(&forward_message));
    assert_eq!(
        forward::destination(&forward_message).unwrap().to_base58(),
        case.forwarded_to.as_deref().unwrap()
    );
    assert_eq!(
        mediator.verkey.to_base58(),
        case.mediator_verkey_base58.as_deref().unwrap()
    );

    // Inner layer: authcrypt to Bob.
    let inner = forward::extract_payload(&forward_message).expect("inner envelope extracts");
    let authenticated = unpack(&inner, &[bob], &bindings)
        .expect("bob opens the inner envelope")
        .require_authenticated()
        .expect("attributable");

    assert_eq!(authenticated.sender.as_str(), "did:example:alice");
    let decrypted: Value =
        serde_json::from_slice(&authenticated.message.to_json().unwrap()).unwrap();
    assert_eq!(decrypted, case.expected_plaintext);
}

/// A Credo envelope addressed to somebody else must not open, and must fail as
/// "not a recipient" rather than as a crypto error that leaks partial progress.
#[test]
fn refuses_a_credo_envelope_addressed_to_another_party() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let case = case(&fixtures, "authcrypt_basic_message");

    let stranger = PrivateIdentity::generate("did:example:stranger").unwrap();
    let mut bindings = DIDCommV1Store::new();
    bindings.add_resolved(parties["alice"].to_resolved());

    assert!(unpack(&envelope_json(case), &[&stranger], &bindings).is_err());
}

/// Tampering with a genuine Credo envelope must be rejected. Exercised against
/// real bytes rather than our own output, so it also confirms we compute the
/// AAD over the same header representation Credo does.
#[test]
fn rejects_a_tampered_credo_envelope() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let case = case(&fixtures, "authcrypt_basic_message");

    let mut bindings = DIDCommV1Store::new();
    bindings.add_resolved(parties["alice"].to_resolved());

    let mut envelope = case.envelope.clone();
    let ciphertext = envelope["ciphertext"].as_str().unwrap().to_string();
    // Flip one base64 character.
    let mut chars: Vec<char> = ciphertext.chars().collect();
    chars[0] = if chars[0] == 'A' { 'B' } else { 'A' };
    envelope["ciphertext"] = Value::String(chars.into_iter().collect());

    let tampered = serde_json::to_string(&envelope).unwrap();
    assert!(unpack(&tampered, &[&parties["bob"]], &bindings).is_err());
}

/// Structural agreement with Credo, asserted directly rather than only implied
/// by a successful decrypt — so a future change that still round-trips against
/// itself but drifts from the wire format is caught.
#[test]
fn our_envelope_layout_matches_credos() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let credo = case(&fixtures, "authcrypt_basic_message");

    let ours: Value = serde_json::from_str(
        &pack::pack_encrypted_authcrypt(
            &BasicMessage::new("structural").unwrap().finalize(),
            &parties["alice"],
            &[parties["bob"].verkey],
        )
        .unwrap(),
    )
    .unwrap();

    let decode = |value: &Value, field: &str| -> Vec<u8> {
        use base64::Engine;
        base64::engine::general_purpose::URL_SAFE_NO_PAD
            .decode(value[field].as_str().unwrap())
            .unwrap_or_else(|_| panic!("`{field}` must be unpadded base64url"))
    };

    // Same field set, same lengths for every fixed-size component.
    assert_eq!(
        decode(&ours, "iv").len(),
        decode(&credo.envelope, "iv").len()
    );
    assert_eq!(
        decode(&ours, "iv").len(),
        12,
        "ChaCha20-Poly1305 IETF nonce"
    );
    assert_eq!(
        decode(&ours, "tag").len(),
        decode(&credo.envelope, "tag").len()
    );

    let header =
        |value: &Value| -> Value { serde_json::from_slice(&decode(value, "protected")).unwrap() };
    let ours_header = header(&ours);
    let credo_header = header(&credo.envelope);

    assert_eq!(ours_header["enc"], credo_header["enc"]);
    assert_eq!(ours_header["typ"], credo_header["typ"]);
    assert_eq!(ours_header["alg"], credo_header["alg"]);

    let ours_recipient = &ours_header["recipients"][0];
    let credo_recipient = &credo_header["recipients"][0];
    assert_eq!(
        ours_recipient["header"]["kid"], credo_recipient["header"]["kid"],
        "both address Bob by the same base58 verkey"
    );
    assert_eq!(
        decode(ours_recipient, "encrypted_key").len(),
        decode(credo_recipient, "encrypted_key").len(),
        "the wrapped CEK length must match Credo's"
    );
    assert_eq!(
        decode(&ours_recipient["header"], "iv").len(),
        decode(&credo_recipient["header"], "iv").len(),
        "crypto_box nonce length must match Credo's"
    );
    assert_eq!(
        decode(&ours_recipient["header"], "sender").len(),
        decode(&credo_recipient["header"], "sender").len(),
        "sealed sender verkey length must match Credo's"
    );
}

/// Write this crate's envelopes for the `interop/didcomm-v1` harness to feed
/// through Credo's `unpackMessage`. Ignored by default: it produces an input
/// for an external tool rather than asserting anything itself.
///
/// ```text
/// cargo test -p affinidi-messaging-didcomm-v1 --test credo_interop \
///     -- --ignored emit_envelopes_for_credo
/// cd interop/didcomm-v1 && npm install && npm run generate
/// ```
#[test]
#[ignore = "writes an artefact for the Credo harness; run explicitly"]
fn emit_envelopes_for_credo() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let alice = &parties["alice"];
    let bob = &parties["bob"];
    let mediator = &parties["mediator"];

    let threaded = BasicMessage::new("packed by affinidi-messaging-didcomm-v1")
        .unwrap()
        .id("rust-msg-1")
        .sent_time("2026-08-08T00:00:00Z")
        .thid("rust-thread-1")
        .pthid("rust-parent-1")
        .finalize();
    let unthreaded: MessageV1 = BasicMessage::new("no thread decorator")
        .unwrap()
        .id("rust-msg-2")
        .finalize();

    let inner = pack::pack_encrypted_authcrypt(&threaded, alice, &[bob.verkey]).unwrap();

    let cases = serde_json::json!({
        "cases": [
            {
                "name": "rust_authcrypt",
                "envelope": serde_json::from_str::<Value>(&inner).unwrap(),
            },
            {
                "name": "rust_anoncrypt",
                "envelope": serde_json::from_str::<Value>(
                    &pack::pack_encrypted_anoncrypt(&threaded, &[bob.verkey]).unwrap()
                ).unwrap(),
            },
            {
                "name": "rust_authcrypt_no_thread",
                "envelope": serde_json::from_str::<Value>(
                    &pack::pack_encrypted_authcrypt(&unthreaded, alice, &[bob.verkey]).unwrap()
                ).unwrap(),
            },
            {
                "name": "rust_authcrypt_multi_recipient",
                "envelope": serde_json::from_str::<Value>(
                    &pack::pack_encrypted_authcrypt(
                        &threaded, alice, &[bob.verkey, mediator.verkey]
                    ).unwrap()
                ).unwrap(),
            },
            {
                "name": "rust_forward_to_mediator",
                "envelope": serde_json::from_str::<Value>(
                    &forward::wrap_in_forward(&bob.verkey, &inner, &mediator.verkey).unwrap()
                ).unwrap(),
            },
        ]
    });

    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../interop/didcomm-v1/rust-envelopes.json"
    );
    std::fs::write(
        path,
        format!("{}\n", serde_json::to_string_pretty(&cases).unwrap()),
    )
    .expect("interop/didcomm-v1 exists");
    println!("wrote {path}");
}

/// Sanity: a `ResolvedIdentity` built from a fixture verkey binds the same way
/// a connection record would, so the DID this crate reports really is the one
/// the caller registered rather than anything read off the wire.
#[test]
fn sender_did_comes_from_the_caller_supplied_binding() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let case = case(&fixtures, "authcrypt_basic_message");

    let alice_verkey = Verkey::from_base58(case.sender_verkey_base58.as_deref().unwrap()).unwrap();

    let mut bindings = DIDCommV1Store::new();
    bindings.add_resolved(
        ResolvedIdentity::new("did:sov:WgWxqztrNooG92RXvxSTWv", alice_verkey).unwrap(),
    );

    let authenticated = unpack(&envelope_json(case), &[&parties["bob"]], &bindings)
        .unwrap()
        .require_authenticated()
        .unwrap();

    assert_eq!(
        authenticated.sender.as_str(),
        "did:sov:WgWxqztrNooG92RXvxSTWv"
    );
    assert_eq!(authenticated.sender_verkey, alice_verkey);
}

/// Without a binding, a genuine Credo authcrypt envelope is authenticated but
/// unattributable — the v1-only third state.
#[test]
fn credo_authcrypt_without_a_binding_is_unattributable() {
    let fixtures = fixtures();
    let parties = parties(&fixtures);
    let case = case(&fixtures, "authcrypt_basic_message");

    let result = unpack(&envelope_json(case), &[&parties["bob"]], &NoBindings).unwrap();
    assert!(result.is_authcrypt());
    assert!(matches!(
        result,
        UnpackResult::AuthcryptUnknownSender { .. }
    ));
}
