use std::{fs, path::Path};

use crate::app::WizardConfig;

const DEFAULT_PORT: u16 = 7037;

/// Generate Dockerfile + .dockerignore + docker-compose.yml so
/// `docker compose up` brings up a self-contained mediator + Redis
/// stack — no external Redis required.
pub fn generate_dockerfile(config: &WizardConfig, output_dir: &str) -> anyhow::Result<()> {
    let features = config.cargo_features();
    let features_flag = if config.needs_explicit_features() {
        format!(" --no-default-features --features {}", features.join(","))
    } else {
        String::new()
    };
    let port = listen_port(&config.listen_address).unwrap_or(DEFAULT_PORT);

    let dockerfile = format!(
        r#"# Affinidi Messaging Mediator
# Generated by mediator-setup

FROM rust:1.94-bookworm AS builder

WORKDIR /build
COPY . .

RUN cargo build --release -p affinidi-messaging-mediator{features_flag}

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/target/release/mediator /usr/local/bin/mediator
COPY --from=builder /build/crates/messaging/affinidi-messaging-mediator/conf /etc/mediator/conf

WORKDIR /etc/mediator

EXPOSE {port}

CMD ["mediator", "-c", "conf/mediator.toml"]
"#
    );

    let dockerignore = r#"target/
.git/
*.md
.github/
.vscode/
.idea/
"#;

    // Two compose templates: one for the Redis-backed deployment
    // (the historical default) and one for the Fjall-backed
    // single-node deployment. The Fjall template skips the bundled
    // Redis service entirely — Fjall's data lives on disk in a
    // mounted volume, so there's no second container to wire up.
    let compose = if config.storage_backend == "fjall" {
        format!(
            r#"# Affinidi Messaging Mediator (Fjall single-node)
# Generated by mediator-setup
#
# Embedded LSM-tree backend; no Redis sidecar. The mediator stores
# state in `/etc/mediator/data` inside the container, mounted from
# the named volume below so data survives `docker compose down`.

services:
  mediator:
    build:
      context: .
      dockerfile: Dockerfile
    image: affinidi-mediator
    volumes:
      - mediator-data:/etc/mediator/data
    ports:
      - "{port}:{port}"
    restart: unless-stopped

volumes:
  mediator-data:
"#
        )
    } else {
        format!(
            r#"# Affinidi Messaging Mediator + Redis
# Generated by mediator-setup
#
# Self-contained stack: `docker compose up` starts the mediator and a
# bundled Redis on a private network. The mediator's `database_url`
# from mediator.toml is overridden via the DATABASE_URL env var so the
# same image still works against an external Redis when run outside of
# compose. Redis is not exposed on the host — only the mediator port
# is published.

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  mediator:
    build:
      context: .
      dockerfile: Dockerfile
    image: affinidi-mediator
    depends_on:
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: redis://redis:6379/
    ports:
      - "{port}:{port}"
    restart: unless-stopped

volumes:
  redis-data:
"#
        )
    };

    fs::create_dir_all(output_dir)?;

    let dockerfile_path = Path::new(output_dir).join("Dockerfile");
    let dockerignore_path = Path::new(output_dir).join(".dockerignore");
    let compose_path = Path::new(output_dir).join("docker-compose.yml");

    fs::write(&dockerfile_path, dockerfile)?;
    fs::write(&dockerignore_path, dockerignore)?;
    fs::write(&compose_path, compose)?;

    println!("\nDocker files generated:");
    println!("  {}", dockerfile_path.display());
    println!("  {}", dockerignore_path.display());
    println!("  {}", compose_path.display());
    println!("\nTo bring up the full stack (mediator + Redis):");
    println!("  docker compose up --build");
    println!("\nMediator listens on http://localhost:{port}");
    println!("Redis is internal to the compose network and not exposed.");

    Ok(())
}

/// Extract the TCP port from a `host:port` listen address. Returns
/// `None` for IPv6 literals or malformed input — callers fall back to
/// [`DEFAULT_PORT`].
fn listen_port(listen_address: &str) -> Option<u16> {
    listen_address.rsplit_once(':')?.1.parse().ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn extracts_port_from_ipv4_listen_address() {
        assert_eq!(listen_port("0.0.0.0:7037"), Some(7037));
        assert_eq!(listen_port("127.0.0.1:8080"), Some(8080));
    }

    #[test]
    fn returns_none_for_unparseable_input() {
        assert_eq!(listen_port("0.0.0.0"), None);
        assert_eq!(listen_port(""), None);
        assert_eq!(listen_port("0.0.0.0:notaport"), None);
    }

    #[test]
    fn dockerfile_for_default_config_uses_default_features() {
        // Default config (didcomm + redis, no explicit secret backend)
        // matches the mediator crate's default features, so the wizard
        // must NOT pass `--no-default-features` — that's what produces
        // the simplest, most cache-friendly Docker build.
        let dir = tempfile::tempdir().unwrap();
        let cfg = WizardConfig::default();
        generate_dockerfile(&cfg, dir.path().to_str().unwrap()).unwrap();

        let dockerfile = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            !dockerfile.contains("--no-default-features"),
            "default config shouldn't override default features:\n{dockerfile}"
        );
        assert!(dockerfile.contains("cargo build --release -p affinidi-messaging-mediator"));
    }

    #[test]
    fn dockerfile_for_fjall_backend_includes_fjall_feature() {
        // Regression: an earlier `build_features` impl forgot to add
        // the storage backend, so a Fjall wizard run produced a
        // Dockerfile that built a binary with no backend at all.
        let dir = tempfile::tempdir().unwrap();
        let mut cfg = WizardConfig::default();
        cfg.storage_backend = "fjall".into();
        generate_dockerfile(&cfg, dir.path().to_str().unwrap()).unwrap();

        let dockerfile = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(
            dockerfile.contains("--no-default-features"),
            "non-default backend choice must override defaults:\n{dockerfile}"
        );
        assert!(
            dockerfile.contains("fjall-backend"),
            "Fjall config must enable fjall-backend feature:\n{dockerfile}"
        );
        assert!(
            !dockerfile.contains("redis-backend"),
            "Fjall config must not enable redis-backend:\n{dockerfile}"
        );
    }

    #[test]
    fn dockerfile_for_redis_with_secret_backend_keeps_redis() {
        // Regression: `redis-backend` is a default feature; when the
        // wizard added a non-default secret backend it triggered
        // `--no-default-features` which silently dropped the storage
        // backend. The fix re-asserts redis-backend explicitly so the
        // binary still has its backend.
        let dir = tempfile::tempdir().unwrap();
        let mut cfg = WizardConfig::default();
        cfg.secret_storage = "aws_secrets://".into();
        generate_dockerfile(&cfg, dir.path().to_str().unwrap()).unwrap();

        let dockerfile = fs::read_to_string(dir.path().join("Dockerfile")).unwrap();
        assert!(dockerfile.contains("--no-default-features"));
        assert!(
            dockerfile.contains("redis-backend"),
            "Redis config must explicitly re-enable redis-backend when \
             --no-default-features is in effect:\n{dockerfile}"
        );
        assert!(dockerfile.contains("secrets-aws"));
    }

    #[test]
    fn compose_for_redis_includes_redis_service() {
        let dir = tempfile::tempdir().unwrap();
        let cfg = WizardConfig::default();
        generate_dockerfile(&cfg, dir.path().to_str().unwrap()).unwrap();
        let compose = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(compose.contains("redis:"));
        assert!(compose.contains("redis:7-alpine"));
        assert!(compose.contains("DATABASE_URL: redis://redis:6379/"));
    }

    #[test]
    fn compose_for_fjall_skips_redis_service() {
        // Regression: Fjall is single-node; the compose file must NOT
        // bundle a Redis sidecar (would be wasted resources) and must
        // mount a named volume for the LSM data directory so state
        // survives `docker compose down`.
        let dir = tempfile::tempdir().unwrap();
        let mut cfg = WizardConfig::default();
        cfg.storage_backend = "fjall".into();
        generate_dockerfile(&cfg, dir.path().to_str().unwrap()).unwrap();
        let compose = fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(
            !compose.contains("redis:7-alpine"),
            "Fjall compose must not bundle Redis:\n{compose}"
        );
        assert!(compose.contains("mediator-data:"));
    }
}
