use std::{fs, path::Path};

use crate::app::WizardConfig;

/// Generate a Dockerfile for the mediator with correct feature flags.
pub fn generate_dockerfile(config: &WizardConfig, output_dir: &str) -> anyhow::Result<()> {
    let features = build_features(config);
    let features_flag = if features.len() == 1 && features[0] == "didcomm" {
        String::new()
    } else {
        format!(" --no-default-features --features {}", features.join(","))
    };

    let dockerfile = format!(
        r#"# Affinidi Messaging Mediator
# Generated by mediator-setup

FROM rust:1.94-bookworm AS builder

WORKDIR /build
COPY . .

RUN cargo build --release -p affinidi-messaging-mediator{features_flag}

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/target/release/affinidi-messaging-mediator /usr/local/bin/mediator
COPY --from=builder /build/crates/messaging/affinidi-messaging-mediator/conf /etc/mediator/conf

WORKDIR /etc/mediator

EXPOSE 7037

CMD ["mediator", "-c", "conf/mediator.toml"]
"#
    );

    let dockerignore = r#"target/
.git/
*.md
.github/
.vscode/
.idea/
"#;

    fs::create_dir_all(output_dir)?;

    let dockerfile_path = Path::new(output_dir).join("Dockerfile");
    let dockerignore_path = Path::new(output_dir).join(".dockerignore");

    fs::write(&dockerfile_path, dockerfile)?;
    fs::write(&dockerignore_path, dockerignore)?;

    println!("\nDocker files generated:");
    println!("  {}", dockerfile_path.display());
    println!("  {}", dockerignore_path.display());
    println!("\nTo build:");
    println!(
        "  docker build -f {} -t affinidi-mediator .",
        dockerfile_path.display()
    );
    println!("\nTo run:");
    println!("  docker run -p 7037:7037 affinidi-mediator");

    Ok(())
}

fn build_features(config: &WizardConfig) -> Vec<&'static str> {
    let mut features = Vec::new();

    if config.didcomm_enabled {
        features.push("didcomm");
    }
    if config.tsp_enabled {
        features.push("tsp");
    }

    match config.secret_storage.as_str() {
        "keyring://" => features.push("vta-keyring"),
        "aws_secrets://" => features.push("vta-aws-secrets"),
        "gcp_secrets://" => features.push("vta-gcp-secrets"),
        "azure_keyvault://" => features.push("vta-azure-keyvault"),
        "vault://" => features.push("vta-hashicorp-vault"),
        _ => {}
    }

    features
}
