use std::{fs, path::Path};

use crate::app::WizardConfig;

const DEFAULT_PORT: u16 = 7037;

/// Generate Dockerfile + .dockerignore + docker-compose.yml so
/// `docker compose up` brings up a self-contained mediator + Redis
/// stack — no external Redis required.
pub fn generate_dockerfile(config: &WizardConfig, output_dir: &str) -> anyhow::Result<()> {
    let features = build_features(config);
    let features_flag = if features.len() == 1 && features[0] == "didcomm" {
        String::new()
    } else {
        format!(" --no-default-features --features {}", features.join(","))
    };
    let port = listen_port(&config.listen_address).unwrap_or(DEFAULT_PORT);

    let dockerfile = format!(
        r#"# Affinidi Messaging Mediator
# Generated by mediator-setup

FROM rust:1.94-bookworm AS builder

WORKDIR /build
COPY . .

RUN cargo build --release -p affinidi-messaging-mediator{features_flag}

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/target/release/mediator /usr/local/bin/mediator
COPY --from=builder /build/crates/messaging/affinidi-messaging-mediator/conf /etc/mediator/conf

WORKDIR /etc/mediator

EXPOSE {port}

CMD ["mediator", "-c", "conf/mediator.toml"]
"#
    );

    let dockerignore = r#"target/
.git/
*.md
.github/
.vscode/
.idea/
"#;

    let compose = format!(
        r#"# Affinidi Messaging Mediator + Redis
# Generated by mediator-setup
#
# Self-contained stack: `docker compose up` starts the mediator and a
# bundled Redis on a private network. The mediator's `database_url`
# from mediator.toml is overridden via the DATABASE_URL env var so the
# same image still works against an external Redis when run outside of
# compose. Redis is not exposed on the host — only the mediator port
# is published.

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  mediator:
    build:
      context: .
      dockerfile: Dockerfile
    image: affinidi-mediator
    depends_on:
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: redis://redis:6379/
    ports:
      - "{port}:{port}"
    restart: unless-stopped

volumes:
  redis-data:
"#
    );

    fs::create_dir_all(output_dir)?;

    let dockerfile_path = Path::new(output_dir).join("Dockerfile");
    let dockerignore_path = Path::new(output_dir).join(".dockerignore");
    let compose_path = Path::new(output_dir).join("docker-compose.yml");

    fs::write(&dockerfile_path, dockerfile)?;
    fs::write(&dockerignore_path, dockerignore)?;
    fs::write(&compose_path, compose)?;

    println!("\nDocker files generated:");
    println!("  {}", dockerfile_path.display());
    println!("  {}", dockerignore_path.display());
    println!("  {}", compose_path.display());
    println!("\nTo bring up the full stack (mediator + Redis):");
    println!("  docker compose up --build");
    println!("\nMediator listens on http://localhost:{port}");
    println!("Redis is internal to the compose network and not exposed.");

    Ok(())
}

/// Extract the TCP port from a `host:port` listen address. Returns
/// `None` for IPv6 literals or malformed input — callers fall back to
/// [`DEFAULT_PORT`].
fn listen_port(listen_address: &str) -> Option<u16> {
    listen_address.rsplit_once(':')?.1.parse().ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_port_from_ipv4_listen_address() {
        assert_eq!(listen_port("0.0.0.0:7037"), Some(7037));
        assert_eq!(listen_port("127.0.0.1:8080"), Some(8080));
    }

    #[test]
    fn returns_none_for_unparseable_input() {
        assert_eq!(listen_port("0.0.0.0"), None);
        assert_eq!(listen_port(""), None);
        assert_eq!(listen_port("0.0.0.0:notaport"), None);
    }
}

fn build_features(config: &WizardConfig) -> Vec<&'static str> {
    let mut features = Vec::new();

    if config.didcomm_enabled {
        features.push("didcomm");
    }
    if config.tsp_enabled {
        features.push("tsp");
    }

    match config.secret_storage.as_str() {
        "keyring://" => features.push("secrets-keyring"),
        "aws_secrets://" => features.push("secrets-aws"),
        "gcp_secrets://" => features.push("secrets-gcp"),
        "azure_keyvault://" => features.push("secrets-azure"),
        "vault://" => features.push("secrets-vault"),
        _ => {}
    }

    features
}
