[package]
name = "did-cheqd"
version = "0.1.0"
description = "Implementation of did:cheqd in Rust"
repository.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
keywords.workspace = true
publish = false
license.workspace = true
readme = "README.md"
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
did_cheqd = { version = "0.1.0", git = "https://github.com/openwallet-foundation/vcx.git", package = "did_cheqd" }
did_resolver = { version = "0.1.0", git = "https://github.com/openwallet-foundation/vcx.git", package = "did_resolver" }
affinidi-did-common.workspace = true
ahash = "0.8"
serde_json = "1.0"
thiserror = "2.0"
url = "2.5"
