use std::{fs, path::Path};

use affinidi_secrets_resolver::secrets::Secret;

use crate::app::WizardConfig;

/// Generated cryptographic material from the wizard generators.
pub struct GeneratedValues {
    /// The mediator's DID string (did:peer:..., vta://..., etc.)
    pub mediator_did: String,
    /// Secrets for the mediator DID
    pub mediator_secrets: Vec<Secret>,
    /// JWT signing secret (base64url-encoded)
    pub jwt_secret: String,
    /// Admin DID (if generated)
    pub admin_did: Option<String>,
    /// Admin secret (if generated — displayed to user, not stored in config)
    pub admin_secret: Option<Secret>,
    /// SSL cert path (if self-signed was generated)
    pub ssl_cert_path: Option<String>,
    /// SSL key path (if self-signed was generated)
    pub ssl_key_path: Option<String>,
}

/// Write the mediator configuration file and any associated secret files.
pub fn write_config(config: &WizardConfig, generated: &GeneratedValues) -> anyhow::Result<()> {
    let toml_content = generate_toml(config, generated)?;

    // Ensure parent directory exists
    let path = Path::new(&config.config_path);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    fs::write(path, &toml_content)?;

    // Write secrets file if using file:// storage
    if config.secret_storage == "file://" {
        let secrets_path = config_dir(config).join("secrets.json");
        crate::generators::secrets::write_secrets_file(
            &generated.mediator_secrets,
            &secrets_path.to_string_lossy(),
        )?;
    }

    Ok(())
}

/// Get the config directory from the config path.
fn config_dir(config: &WizardConfig) -> std::path::PathBuf {
    Path::new(&config.config_path)
        .parent()
        .unwrap_or(Path::new("."))
        .to_path_buf()
}

fn generate_toml(config: &WizardConfig, generated: &GeneratedValues) -> anyhow::Result<String> {
    let mut out = String::new();

    // Header
    out.push_str("### Mediator Configuration\n");
    out.push_str("### Generated by mediator-setup\n\n");

    // Log level
    out.push_str("log_level = \"info\"\n\n");

    // Mediator DID
    out.push_str(&format!(
        "mediator_did = \"did://{}\"\n\n",
        generated.mediator_did
    ));

    // VTA section (if VTA is used for DID or secrets)
    if config.did_method == "VTA managed" || config.secret_storage == "vta://" {
        out.push_str("[vta]\n");
        out.push_str("credential = \"keyring://affinidi-mediator/vta-credential\"\n");
        out.push_str("context = \"mediator\"\n\n");
    }

    // Server section
    out.push_str("[server]\n");
    out.push_str(&format!("listen_address = \"{}\"\n", config.listen_address));
    out.push_str("api_prefix = \"/mediator/v1/\"\n");

    // Admin DID
    if let Some(ref admin_did) = generated.admin_did {
        out.push_str(&format!("admin_did = \"did://{admin_did}\"\n"));
    } else {
        out.push_str("# admin_did = \"did://YOUR_ADMIN_DID_HERE\"\n");
    }

    // Self-hosted DID document
    if config.did_method == "did:webvh" {
        out.push_str("did_web_self_hosted = \"file://./conf/mediator_did.json\"\n");
    }
    out.push('\n');

    // Database section
    out.push_str("[database]\n");
    out.push_str("functions_file = \"./conf/atm-functions.lua\"\n");
    out.push_str(&format!("database_url = \"{}\"\n", config.database_url));
    out.push_str("database_timeout = \"2\"\n\n");

    // Security section
    out.push_str("[security]\n");
    out.push_str("mediator_acl_mode = \"explicit_allow\"\n");
    out.push_str("global_acl_default = \"DENY_ALL,LOCAL,SEND_MESSAGES,RECEIVE_MESSAGES\"\n");

    // Mediator secrets
    let secrets_ref = match config.secret_storage.as_str() {
        "string://" => {
            let b64 = crate::generators::secrets::secrets_to_base64(&generated.mediator_secrets)?;
            format!("string://{b64}")
        }
        "file://" => "file://./conf/secrets.json".into(),
        "keyring://" => "keyring://affinidi-mediator/secrets".into(),
        "aws_secrets://" => "aws_secrets://mediator/secrets".into(),
        "gcp_secrets://" => "gcp_secrets://mediator/secrets".into(),
        "azure_keyvault://" => "azure_keyvault://mediator-secrets".into(),
        "vault://" => "vault://secret/mediator/secrets".into(),
        "vta://" => "vta://mediator".into(),
        other => other.to_string(),
    };
    out.push_str(&format!("mediator_secrets = \"{secrets_ref}\"\n"));

    // SSL
    match config.ssl_mode.as_str() {
        "No SSL (TLS proxy)" => {
            out.push_str("use_ssl = \"false\"\n");
        }
        "Existing certificates" => {
            out.push_str("use_ssl = \"true\"\n");
            out.push_str(&format!(
                "ssl_certificate_file = \"{}\"\n",
                config.ssl_cert_path
            ));
            out.push_str(&format!("ssl_key_file = \"{}\"\n", config.ssl_key_path));
        }
        "Self-signed" => {
            out.push_str("use_ssl = \"true\"\n");
            let cert = generated
                .ssl_cert_path
                .as_deref()
                .unwrap_or("conf/keys/end.cert");
            let key = generated
                .ssl_key_path
                .as_deref()
                .unwrap_or("conf/keys/end.key");
            out.push_str(&format!("ssl_certificate_file = \"{cert}\"\n"));
            out.push_str(&format!("ssl_key_file = \"{key}\"\n"));
        }
        _ => {
            out.push_str("use_ssl = \"false\"\n");
        }
    }

    // JWT
    out.push_str(&format!(
        "jwt_authorization_secret = \"string://{}\"\n",
        generated.jwt_secret
    ));
    out.push_str("jwt_access_expiry = \"900\"\n");
    out.push_str("jwt_refresh_expiry = \"86400\"\n");
    out.push_str("block_anonymous_outer_envelope = \"true\"\n");
    out.push_str("force_session_did_match = \"true\"\n");
    out.push_str("block_remote_admin_msgs = \"true\"\n");
    out.push_str("admin_messages_expiry = \"3\"\n\n");

    // Streaming
    out.push_str("[streaming]\n");
    out.push_str("enabled = \"true\"\n");
    out.push_str("uuid = \"hostname://\"\n\n");

    // DID Resolver
    out.push_str("[did_resolver]\n");
    out.push_str("cache_capacity = \"1000\"\n");
    out.push_str("cache_ttl = \"300\"\n");
    out.push_str("network_timeout = \"5000\"\n");
    out.push_str("network_limit = \"100\"\n\n");

    // Limits — sensible defaults
    out.push_str("[limits]\n");
    out.push_str("attachments_max_count = \"20\"\n");
    out.push_str("crypto_operations_per_message = \"1000\"\n");
    out.push_str("deleted_messages = \"100\"\n");
    out.push_str("forward_task_queue = \"50000\"\n");
    out.push_str("http_size = \"10485760\"\n");
    out.push_str("listed_messages = \"100\"\n");
    out.push_str("local_max_acl = \"1000\"\n");
    out.push_str("message_expiry_seconds = \"604800\"\n");
    out.push_str("message_size = \"1048576\"\n");
    out.push_str("queued_send_messages_soft = \"200\"\n");
    out.push_str("queued_send_messages_hard = \"1000\"\n");
    out.push_str("queued_receive_messages_soft = \"200\"\n");
    out.push_str("queued_receive_messages_hard = \"1000\"\n");
    out.push_str("to_keys_per_recipient = \"100\"\n");
    out.push_str("to_recipients = \"100\"\n");
    out.push_str("ws_size = \"10485760\"\n");
    out.push_str("access_list_limit = \"1000\"\n");
    out.push_str("oob_invite_ttl = \"86400\"\n\n");

    // Forwarding processor
    out.push_str("[processors.forwarding]\n");
    out.push_str("enabled = \"true\"\n");
    out.push_str("future_time_limit = \"86400\"\n");
    out.push_str("external_forwarding = \"true\"\n");
    out.push_str("report_errors = \"true\"\n");
    out.push_str("blocked_forwarding_dids = \"[]\"\n");
    out.push_str("rate_window_seconds = \"300\"\n");
    out.push_str("ws_threshold_msgs_per_10s = \"1\"\n");
    out.push_str("ws_idle_timeout_seconds = \"60\"\n");
    out.push_str("batch_size = \"50\"\n");
    out.push_str("max_retries = \"5\"\n");
    out.push_str("initial_backoff_ms = \"1000\"\n");
    out.push_str("max_backoff_ms = \"60000\"\n");
    out.push_str("consumer_group = \"forwarding\"\n\n");

    // Message expiry cleanup
    out.push_str("[processors.message_expiry_cleanup]\n");
    out.push_str("enabled = \"true\"\n");

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_generated() -> GeneratedValues {
        GeneratedValues {
            mediator_did: "did:peer:2.Vtest.Etest".into(),
            mediator_secrets: vec![],
            jwt_secret: "test_jwt_secret_base64url".into(),
            admin_did: Some("did:key:z6MkTest".into()),
            admin_secret: None,
            ssl_cert_path: None,
            ssl_key_path: None,
        }
    }

    #[test]
    fn test_generate_toml_local_dev() {
        let config = WizardConfig {
            config_path: "conf/mediator.toml".into(),
            deployment_type: "Local development".into(),
            protocol: "DIDComm v2".into(),
            did_method: "did:peer".into(),
            public_url: String::new(),
            secret_storage: "string://".into(),
            ssl_mode: "No SSL (TLS proxy)".into(),
            ssl_cert_path: String::new(),
            ssl_key_path: String::new(),
            database_url: "redis://127.0.0.1/".into(),
            admin_did_mode: "Generate did:key".into(),
            listen_address: "0.0.0.0:7037".into(),
        };

        let toml = generate_toml(&config, &test_generated()).unwrap();
        assert!(toml.contains("mediator_did = \"did://did:peer:2.Vtest.Etest\""));
        assert!(toml.contains("use_ssl = \"false\""));
        assert!(toml.contains("database_url = \"redis://127.0.0.1/\""));
        assert!(toml.contains("[security]"));
        assert!(toml.contains("[database]"));
        assert!(toml.contains("[processors.forwarding]"));
        assert!(toml.contains("jwt_authorization_secret = \"string://test_jwt_secret_base64url\""));
        assert!(toml.contains("admin_did = \"did://did:key:z6MkTest\""));
    }

    #[test]
    fn test_generate_toml_vta() {
        let config = WizardConfig {
            config_path: "conf/mediator.toml".into(),
            deployment_type: "Headless server".into(),
            protocol: "DIDComm v2".into(),
            did_method: "VTA managed".into(),
            public_url: "https://mediator.example.com/mediator/v1".into(),
            secret_storage: "vta://".into(),
            ssl_mode: "No SSL (TLS proxy)".into(),
            ssl_cert_path: String::new(),
            ssl_key_path: String::new(),
            database_url: "redis://redis.example.com/".into(),
            admin_did_mode: "Generate did:key".into(),
            listen_address: "0.0.0.0:7037".into(),
        };

        let generated = GeneratedValues {
            mediator_did: "vta://mediator".into(),
            mediator_secrets: vec![],
            jwt_secret: "test_jwt".into(),
            admin_did: Some("did:key:z6MkTest".into()),
            admin_secret: None,
            ssl_cert_path: None,
            ssl_key_path: None,
        };

        let toml = generate_toml(&config, &generated).unwrap();
        assert!(toml.contains("[vta]"));
        assert!(toml.contains("mediator_secrets = \"vta://mediator\""));
    }
}
