//! Ephemeral Ed25519 `did:key` generated by the wizard for a single setup
//! session.
//!
//! The setup key is held in memory for the lifetime of the wizard process.
//! On wizard restart a fresh key is generated and the operator must re-run
//! the `pnm acl create` step for the new DID, *unless* the key was persisted
//! via `--setup-key-out` and reloaded via `--setup-key-file`. The latter is
//! how the two-phase non-interactive flow bridges the race between ACL
//! provisioning and connection verification.

use std::fs;
use std::path::Path;

#[cfg(unix)]
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};

use affinidi_tdk::dids::{DID, KeyType};
use serde::{Deserialize, Serialize};

/// On-disk representation. Kept deliberately small — only the two strings
/// the auth paths actually consume.
#[derive(Debug, Serialize, Deserialize)]
struct PersistedKey {
    version: u8,
    did: String,
    private_key_multibase: String,
    #[serde(default)]
    note: String,
}

pub struct EphemeralSetupKey {
    pub did: String,
    private_key_mb: String,
}

impl EphemeralSetupKey {
    pub fn generate() -> anyhow::Result<Self> {
        let (did, secret) = DID::generate_did_key(KeyType::Ed25519)
            .map_err(|e| anyhow::anyhow!("generate did:key: {e}"))?;
        let private_key_mb = secret
            .get_private_keymultibase()
            .map_err(|e| anyhow::anyhow!("get private key multibase: {e}"))?;
        Ok(Self {
            did,
            private_key_mb,
        })
    }

    pub fn private_key_multibase(&self) -> &str {
        &self.private_key_mb
    }

    /// Persist to a JSON file with owner-only permissions (unix). Used by
    /// `mediator-setup --setup-key-out <path>` so the operator can complete
    /// ACL registration between wizard invocations.
    pub fn persist_to(&self, path: &Path) -> anyhow::Result<()> {
        let payload = PersistedKey {
            version: 1,
            did: self.did.clone(),
            private_key_multibase: self.private_key_mb.clone(),
            note: "Ephemeral setup key for mediator-setup. \
                   Delete once the mediator is provisioned."
                .into(),
        };
        let json = serde_json::to_string_pretty(&payload)?;

        let mut opts = fs::OpenOptions::new();
        opts.create(true).write(true).truncate(true);
        #[cfg(unix)]
        opts.mode(0o600);
        let mut file = opts.open(path)?;
        use std::io::Write;
        file.write_all(json.as_bytes())?;
        #[cfg(unix)]
        {
            let mut perm = fs::metadata(path)?.permissions();
            perm.set_mode(0o600);
            fs::set_permissions(path, perm)?;
        }
        Ok(())
    }

    /// Reload a previously-persisted setup key.
    pub fn load_from(path: &Path) -> anyhow::Result<Self> {
        let bytes = fs::read(path)
            .map_err(|e| anyhow::anyhow!("read setup key from {}: {e}", path.display()))?;
        let p: PersistedKey = serde_json::from_slice(&bytes)
            .map_err(|e| anyhow::anyhow!("parse setup key {}: {e}", path.display()))?;
        if p.version != 1 {
            anyhow::bail!(
                "unsupported setup key version {} in {}",
                p.version,
                path.display()
            );
        }
        Ok(Self {
            did: p.did,
            private_key_mb: p.private_key_multibase,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::NamedTempFile;

    #[test]
    fn generate_returns_did_key_with_private_multibase() {
        let key = EphemeralSetupKey::generate().unwrap();
        assert!(key.did.starts_with("did:key:z6Mk"));
        assert!(!key.private_key_multibase().is_empty());
    }

    #[test]
    fn two_generate_calls_produce_distinct_keys() {
        let a = EphemeralSetupKey::generate().unwrap();
        let b = EphemeralSetupKey::generate().unwrap();
        assert_ne!(a.did, b.did);
    }

    #[test]
    fn persist_roundtrip_preserves_did_and_key() {
        let tmp = NamedTempFile::new().unwrap();
        let original = EphemeralSetupKey::generate().unwrap();
        original.persist_to(tmp.path()).unwrap();
        let reloaded = EphemeralSetupKey::load_from(tmp.path()).unwrap();
        assert_eq!(original.did, reloaded.did);
        assert_eq!(
            original.private_key_multibase(),
            reloaded.private_key_multibase()
        );
    }

    #[cfg(unix)]
    #[test]
    fn persisted_file_has_owner_only_permissions() {
        use std::os::unix::fs::PermissionsExt;
        let tmp = NamedTempFile::new().unwrap();
        let key = EphemeralSetupKey::generate().unwrap();
        key.persist_to(tmp.path()).unwrap();
        let perm = fs::metadata(tmp.path()).unwrap().permissions();
        assert_eq!(perm.mode() & 0o777, 0o600);
    }

    #[test]
    fn load_rejects_unknown_version() {
        let tmp = NamedTempFile::new().unwrap();
        std::fs::write(
            tmp.path(),
            r#"{"version":42,"did":"did:key:z6Mk","private_key_multibase":"z"}"#,
        )
        .unwrap();
        assert!(EphemeralSetupKey::load_from(tmp.path()).is_err());
    }
}
