// Credo conformance for coordinate-mediation 1.0 and message-pickup 2.0.
//
// Run via `run.mjs`. Two halves, mirroring the envelope interop in
// `generate.mjs`:
//
// **Credo -> us.** Builds each request with Credo's *real* message classes and
// writes their JSON to the committed fixtures the mediator's e2e test replays.
// So the requests the mediator is tested against are the ones Credo actually
// emits — field names, decorators and all — rather than our reading of the RFC.
//
// **Us -> Credo.** Reads the replies the mediator produced
// (`rust-mediation-replies.json`, written by the e2e test) and parses each one
// through `JsonTransformer.fromJSON` against the matching Credo class. That
// call *validates*: wrong member name, wrong casing, a missing required field
// or an out-of-spec `@id` all throw. It is the assertion that Credo would
// accept what we send.
//
// This is the layer the envelope interop does not reach. Packing and unpacking
// are already proven against live Credo output in `generate.mjs`; what is
// unproven without this is whether the *messages inside* are shaped the way
// Credo expects.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { JsonTransformer, utils } from '@credo-ts/core'
import {
  DidCommDeliveryRequestV2Message,
  DidCommKeylistUpdate,
  DidCommKeylistUpdateAction,
  DidCommKeylistUpdateMessage,
  DidCommKeylistUpdateResponseMessage,
  DidCommMediationDenyMessage,
  DidCommMediationGrantMessage,
  DidCommMediationRequestMessage,
  DidCommMessageDeliveryV2Message,
  DidCommMessagesReceivedV2Message,
  DidCommStatusRequestV2Message,
  DidCommStatusV2Message,
} from '@credo-ts/didcomm'

/** Requests replayed by the mediator's e2e test. */
const REQUESTS_PATH = new URL(
  '../../crates/messaging/affinidi-messaging-test-mediator/tests/fixtures/credo_mediation.json',
  import.meta.url
)
/** Replies recorded by that test, for the reverse direction. */
const REPLIES_PATH = new URL('./rust-mediation-replies.json', import.meta.url)

// A recipient key to register. Credo emits did:key here by default, which is
// exactly the spelling we want the mediator exercised against.
const RECIPIENT_DID_KEY = 'did:key:z6MkoM4yQaj3DCZF7FDiE4YQA8ZVwHnn2Y8xi5KncwfjAyXk'

// ── Credo -> us: build the requests ─────────────────────────────────────────

const requests = [
  {
    name: 'mediate_request',
    expectReply: 'mediate-grant',
    message: new DidCommMediationRequestMessage({}).toJSON(),
  },
  {
    name: 'keylist_update_add',
    expectReply: 'keylist-update-response',
    // did:key spelling — the RFC 0211 form, and Credo's default.
    recipientKey: RECIPIENT_DID_KEY,
    message: new DidCommKeylistUpdateMessage({
      updates: [
        new DidCommKeylistUpdate({
          recipientKey: RECIPIENT_DID_KEY,
          action: DidCommKeylistUpdateAction.add,
        }),
      ],
    }).toJSON(),
  },
  {
    name: 'keylist_update_remove',
    expectReply: 'keylist-update-response',
    recipientKey: RECIPIENT_DID_KEY,
    message: new DidCommKeylistUpdateMessage({
      updates: [
        new DidCommKeylistUpdate({
          recipientKey: RECIPIENT_DID_KEY,
          action: DidCommKeylistUpdateAction.remove,
        }),
      ],
    }).toJSON(),
  },
  {
    name: 'status_request',
    expectReply: 'status',
    message: new DidCommStatusRequestV2Message({}).toJSON(),
  },
  {
    name: 'delivery_request',
    expectReply: 'status-or-delivery',
    message: new DidCommDeliveryRequestV2Message({ limit: 10 }).toJSON(),
  },
  {
    name: 'messages_received',
    expectReply: 'status',
    // Filled in by the e2e test with the id it was actually delivered; the
    // shape is what matters here.
    message: new DidCommMessagesReceivedV2Message({
      messageIdList: ['__REPLACE_WITH_DELIVERED_ID__'],
    }).toJSON(),
  },
]

writeFileSync(
  REQUESTS_PATH,
  `${JSON.stringify(
    {
      generator: { credo: '0.6.3', note: 'Generated by interop/didcomm-v1 — do not hand-edit.' },
      requests,
    },
    null,
    2
  )}\n`
)
console.log(`wrote ${requests.length} Credo-built mediation requests`)

// Sanity: every request must round-trip through its own Credo class, or the
// fixture is not what Credo would send.
const requestClasses = {
  mediate_request: DidCommMediationRequestMessage,
  keylist_update_add: DidCommKeylistUpdateMessage,
  keylist_update_remove: DidCommKeylistUpdateMessage,
  status_request: DidCommStatusRequestV2Message,
  delivery_request: DidCommDeliveryRequestV2Message,
  messages_received: DidCommMessagesReceivedV2Message,
}
for (const request of requests) {
  JsonTransformer.fromJSON(request.message, requestClasses[request.name])
}
console.log('self-check: every generated request validates against its Credo class')

// ── Us -> Credo: validate the mediator's replies ────────────────────────────

/** Reply `@type` (either document-URI spelling) -> the Credo class for it. */
const replyClasses = [
  ['coordinate-mediation/1.0/mediate-grant', DidCommMediationGrantMessage],
  ['coordinate-mediation/1.0/mediate-deny', DidCommMediationDenyMessage],
  ['coordinate-mediation/1.0/keylist-update-response', DidCommKeylistUpdateResponseMessage],
  ['messagepickup/2.0/status', DidCommStatusV2Message],
  ['messagepickup/2.0/delivery', DidCommMessageDeliveryV2Message],
]

function classFor(type) {
  const match = replyClasses.find(([suffix]) => type.endsWith(suffix))
  return match?.[1]
}

if (!existsSync(REPLIES_PATH)) {
  console.log('no rust-mediation-replies.json — skipping the us -> Credo direction')
} else {
  const { replies } = JSON.parse(readFileSync(REPLIES_PATH, 'utf8'))
  let failed = 0

  for (const { name, reply } of replies) {
    const type = reply['@type']
    const Class = classFor(type)
    if (!Class) {
      console.error(`  FAILED ${name}: no Credo class matches @type ${type}`)
      failed++
      continue
    }

    try {
      // Validates as well as parses: a wrong member name, wrong casing, a
      // missing required field or an out-of-spec @id all throw here.
      const parsed = JsonTransformer.fromJSON(reply, Class)
      // Re-serialising and re-parsing catches a field Credo dropped silently
      // on the way in — it would vanish rather than round-trip.
      JsonTransformer.fromJSON(parsed.toJSON(), Class)
      console.log(`  ok ${name}: Credo accepts ${type.split('/').slice(-2).join('/')}`)
    } catch (error) {
      console.error(`  FAILED ${name} (${type}): ${error?.message ?? error}`)
      failed++
    }
  }

  console.log(`Credo validated ${replies.length - failed}/${replies.length} mediator replies`)
  if (failed) process.exitCode = 1
}

// `utils` is imported for its side-effect-free id helpers in future additions;
// referencing it keeps the import honest under lint.
void utils
