[package]
name = "did-webvh"
version = "0.1.4"
description = "Implementation of the did:webvh method in Rust, uses the ssi crate"
repository.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
keywords.workspace = true
publish.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# cannot use workspace due to cyclic dependencies
affinidi-data-integrity.workspace = true
affinidi-secrets-resolver.workspace = true

ahash = { version = "0.8", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
multibase = "0.9"
multihash = "0.19"
reqwest = "0.12"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_json_canonicalizer = "0.3.0"
serde_with = "3.12"
sha2 = "0.10"
ssi = { version = "0.12", features = ["secp384r1"] }
thiserror = "2.0"
tracing = { version = "0.1", features = [
  "max_level_debug",
  "release_max_level_info",
] }
url = "2.5"

[dev-dependencies]
affinidi-tdk.workspace = true

anyhow = "1.0"
console = "0.15"
dialoguer = "0.11"
iref = { version = "3.2.2", features = ["serde"] }
tokio = { version = "1.45", features = ["full"] }
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "fmt",
  "json",
  "valuable",
] }
