[package]
name = "did-webvh"
version = "0.1.0"
description = "Implementation of the did:webvh method in Rust, uses the ssi crate"
repository.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
keywords.workspace = true
publish.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
ssi = { version = "0.11", features = ["secp384r1"] }
thiserror = "2.0"
url = "2.5"

[dev-dependencies]
tokio = { version = "1.44", features = ["full"] }
