[package]
name = "affinidi-messaging-mediator-processors"
version = "0.10.1"
description = "Affinidi Messaging Mediator Processors"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
keywords.workspace = true
publish.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
repository.workspace = true

[lib]
path = "src/lib/lib.rs"

[[bin]]
name = "message_expiry_cleanup"
path = "src/message_expiry_cleanup/main.rs"

[dependencies]
affinidi-messaging-mediator-common.workspace = true
clap = { version = "4.5", features = ["derive"] }
deadpool-redis = { version = "0.20", features = ["rt_tokio_1"] }
serde = { version = "1.0", features = ["derive", "rc"] }
tokio = { version = "1.44", features = ["full"] }
toml = "0.8"
tracing = { version = "0.1", features = [
    "max_level_debug",
    "release_max_level_info",
    "valuable",
] }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "fmt",
    "json",
    "valuable",
] }
