//! Routing / Forward 1.0 (Aries RFC 0094).
//!
//! Mirrors [`affinidi_messaging_didcomm::message::forward`]. The v1 forward
//! differs from v2.1's `https://didcomm.org/routing/2.0/forward` in three ways
//! that all bite at once:
//!
//! - the type URI is `did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/routing/1.0/forward`;
//! - the destination member is `to`, holding a **base58 verkey**, not a DID;
//! - the payload member is `msg`, holding the inner envelope **inline as a JSON
//!   object** — v2.1 puts it in an `attachments` array.
//!
//! A forward is always anoncrypt'd to the routing key: the mediator is not
//! meant to learn who the sender is, only where to pass the envelope.

use serde_json::Value;

use crate::error::DIDCommV1Error;
use crate::identity::Verkey;
use crate::message::{MessageV1, TypeFormat, types_match};
use crate::{envelope, message::pack};

/// The Forward 1.0 type URI, in v1's legacy `did:sov` form — what
/// [`build_forward`] emits by default.
///
/// The equivalent modern form is [`FORWARD_TYPE_DIDCOMM_ORG`], and that is what
/// Credo actually sends: a forward generated by a live Credo agent arrives as
/// `https://didcomm.org/routing/1.0/forward`. Compare with [`is_forward`],
/// never with `==`.
pub const FORWARD_TYPE: &str = "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/routing/1.0/forward";

/// The Forward 1.0 type URI in the RFC 0348 form.
pub const FORWARD_TYPE_DIDCOMM_ORG: &str = "https://didcomm.org/routing/1.0/forward";

/// Build a forward message wrapping an already-packed envelope.
///
/// `to` is the **verkey the inner envelope is addressed to**, not the routing
/// key it is being handed to.
pub fn build_forward(to: &Verkey, inner_envelope: &str) -> Result<MessageV1, DIDCommV1Error> {
    let msg: Value = serde_json::from_str(inner_envelope).map_err(|e| {
        DIDCommV1Error::InvalidMessage(format!("forward payload is not a JSON envelope: {e}"))
    })?;

    MessageV1::new(
        FORWARD_TYPE,
        serde_json::json!({ "to": to.to_base58(), "msg": msg }),
    )
}

/// Wrap `inner_envelope` in a forward and anoncrypt it to `routing_key`.
///
/// The one-call path for sending through a mediator. Apply repeatedly, outermost
/// last, for a multi-hop route.
pub fn wrap_in_forward(
    to: &Verkey,
    inner_envelope: &str,
    routing_key: &Verkey,
) -> Result<String, DIDCommV1Error> {
    let forward = build_forward(to, inner_envelope)?;
    pack::pack_encrypted_anoncrypt(&forward, &[*routing_key])
}

/// Whether `msg` is a forward, in either document-URI form.
pub fn is_forward(msg: &MessageV1) -> bool {
    types_match(&msg.typ, FORWARD_TYPE)
}

/// [`build_forward`] emitting the given document-URI form.
pub fn build_forward_with_format(
    to: &Verkey,
    inner_envelope: &str,
    format: TypeFormat,
) -> Result<MessageV1, DIDCommV1Error> {
    Ok(build_forward(to, inner_envelope)?.with_type_format(format))
}

/// The inner envelope carried by a forward, ready to unpack.
pub fn extract_payload(msg: &MessageV1) -> Result<String, DIDCommV1Error> {
    if !is_forward(msg) {
        return Err(DIDCommV1Error::InvalidMessage(format!(
            "expected a forward message, got `{}`",
            msg.typ
        )));
    }
    let inner = msg.body.get("msg").ok_or_else(|| {
        DIDCommV1Error::InvalidMessage("forward message has no `msg` member".into())
    })?;

    if !envelope::is_envelope(inner) {
        return Err(DIDCommV1Error::InvalidMessage(
            "forward `msg` is not a v1 envelope".into(),
        ));
    }
    serde_json::to_string(inner)
        .map_err(|e| DIDCommV1Error::Serialization(format!("forward payload: {e}")))
}

/// The verkey a forward is destined for.
pub fn destination(msg: &MessageV1) -> Result<Verkey, DIDCommV1Error> {
    let to = msg.body.get("to").and_then(Value::as_str).ok_or_else(|| {
        DIDCommV1Error::InvalidMessage("forward message has no `to` member".into())
    })?;
    Verkey::from_base58(to)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::identity::PrivateIdentity;
    use crate::message::unpack::{NoBindings, UnpackResult, unpack};
    use crate::store::DIDCommV1Store;

    fn message() -> MessageV1 {
        crate::protocols::basic_message::BasicMessage::new("hi")
            .unwrap()
            .finalize()
    }

    #[test]
    fn forwarded_message_reaches_its_destination() {
        let alice = PrivateIdentity::generate("did:example:alice").unwrap();
        let bob = PrivateIdentity::generate("did:example:bob").unwrap();
        let mediator = PrivateIdentity::generate("did:example:mediator").unwrap();

        let mut bob_bindings = DIDCommV1Store::new();
        bob_bindings.add_resolved(alice.to_resolved());

        // Alice authcrypts to Bob, then anoncrypts a forward to the mediator.
        let inner = pack::pack_encrypted_authcrypt(&message(), &alice, &[bob.verkey]).unwrap();
        let outer = wrap_in_forward(&bob.verkey, &inner, &mediator.verkey).unwrap();

        // The mediator sees only an anonymous forward — no sender.
        let at_mediator = unpack(&outer, &[&mediator], &NoBindings).unwrap();
        assert!(
            matches!(at_mediator, UnpackResult::Anoncrypt { .. }),
            "a forward must not reveal the sender to the mediator"
        );

        let forward = at_mediator.into_message();
        assert!(is_forward(&forward));
        assert_eq!(destination(&forward).unwrap(), bob.verkey);

        // Bob unpacks the inner envelope and sees Alice.
        let payload = extract_payload(&forward).unwrap();
        match unpack(&payload, &[&bob], &bob_bindings).unwrap() {
            UnpackResult::Authcrypt {
                sender, message, ..
            } => {
                assert_eq!(sender.as_str(), "did:example:alice");
                assert_eq!(message.body["content"], "hi");
            }
            other => panic!("expected Authcrypt, got {other:?}"),
        }
    }

    #[test]
    fn payload_is_inline_json_not_an_attachment() {
        let bob = PrivateIdentity::generate("did:example:bob").unwrap();
        let inner = pack::pack_encrypted_anoncrypt(&message(), &[bob.verkey]).unwrap();
        let forward = build_forward(&bob.verkey, &inner).unwrap();

        let wire: Value = serde_json::from_slice(&forward.to_json().unwrap()).unwrap();
        assert_eq!(wire["@type"], FORWARD_TYPE);
        assert!(wire["to"].is_string(), "`to` is a base58 verkey string");
        assert!(
            wire["msg"].is_object(),
            "v1 carries the inner envelope inline, not in `attachments`"
        );
        assert!(wire.get("attachments").is_none());
    }

    /// Credo sends `https://didcomm.org/routing/1.0/forward`, not the
    /// `did:sov:` form almost every example shows. Both must be recognised.
    #[test]
    fn recognises_both_forward_type_uri_forms() {
        let bob = PrivateIdentity::generate("did:example:bob").unwrap();
        let inner = pack::pack_encrypted_anoncrypt(&message(), &[bob.verkey]).unwrap();

        let legacy = build_forward(&bob.verkey, &inner).unwrap();
        assert_eq!(legacy.typ, FORWARD_TYPE);
        assert!(is_forward(&legacy));

        let modern =
            build_forward_with_format(&bob.verkey, &inner, TypeFormat::DidCommOrg).unwrap();
        assert_eq!(modern.typ, FORWARD_TYPE_DIDCOMM_ORG);
        assert!(
            is_forward(&modern),
            "a Credo-style forward @type must be recognised"
        );
        assert_eq!(destination(&modern).unwrap(), bob.verkey);
        assert!(extract_payload(&modern).is_ok());
    }

    #[test]
    fn rejects_a_non_forward_and_a_non_envelope_payload() {
        assert!(extract_payload(&message()).is_err());

        let mut forward = build_forward(
            &Verkey::from_bytes([1u8; 32]),
            r#"{"protected":"x","iv":"y","ciphertext":"z","tag":"t"}"#,
        )
        .unwrap();
        forward
            .body
            .insert("msg".into(), serde_json::json!({"not": "an envelope"}));
        assert!(extract_payload(&forward).is_err());
    }
}
